name: tests
on:
  push:

  schedule:
    # Daily 5am australian/brisbane time (7pm UTC)
    - cron: '0 19 * * *'

jobs:
  plugin-tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: buildkite/plugin-tester:v1.1.0
      volumes:
        - "${{github.workspace}}:/plugin"
    steps:
      - uses: actions/checkout@v3
      - name: tests
        run: bats tests/
  plugin-lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: buildkite/plugin-linter:latest
      volumes:
        - "${{github.workspace}}:/plugin"
    steps:
      - uses: actions/checkout@v3
      - name: lint
        run: lint --id OctopusDeploy/push-build-information
  plugin-shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.2.0
        with:
          check_together: 'yes'